
title: Liquid Eye
title_long: Liquid Eye Water Housing Systems
slogan: Rock solid yet light as a feather!
email: contact@liquideye.co
description: > # this means to ignore newlines until "baseurl:"
  Liquid Eye produces light and strong waterproof housing systems for both DSLR and mirrorless cameras. Whether you shooting surfing, windsurfing, bodyboarding, swimming, kayaking and you are a beginner or an expert surf photographer, Liquid Eye has the waterhousing solution to suit your needs. Our housing are conceived and designed by professional photographers and manufactured to last a lifetime. We ship internationally!
baseurl: ""
url: "http://liquideye.co"
preview_image: liquideye_social.jpg
version: 0.9.7

github_url: "https://toybreaker.github.io/liquideye"
github_username:  toybreaker
repository: toybreaker/liquideye
instagram: liquideyewaterhousings
facebook: LiquidEyeWaterHousingSystem
twitter_username: LiquidEye_whs
twitter_creator: rokmatwit

google:
  youtube: LiquidEyeWHS
  analytics: UA-32074745-1
  verification: 2TUcbNnmlT1zmtREN6_kNcFYbfkWTunSuai0CcnfA8I

# i
ui: '256466927'
at: '256466927.928b166.90b119a23d774c3f907536f435af3168'

# Build settings
markdown: kramdown
gems:
 - jekyll-mentions
 - jekyll-redirect-from
 - jekyll-sitemap
 - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
permalink: pretty

collections:
  testimonials:
  team:
   output: true
   permalink: /team/:path/
  waterhousings:
   output: true
   permalink: /water-housings/:path/
  pistols:
   output: true
   permalink: /accessories/pistols/:path/
  grips:
   output: true
   permalink: /accessories/grips/:path/
  ports:
   output: true
   permalink: /accessories/ports/:path/
  spareparts:
   output: true
   permalink: /accessories/spare-parts/:path/
  gearsleeves:
   output: true
   permalink: /accessories/gear-sleeves/:path/
